"""create tables

Revision ID: 51634997b174
Revises: 
Create Date: 2025-06-30 21:10:31.748861

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '51634997b174'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=31), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=31), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('user_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=31), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=31), nullable=False),
                    sa.Column('password', sa.String(length=2047), nullable=False),
                    sa.Column('salt', sa.String(length=7), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['user_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chats',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=31), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['status_id'], ['chat_statuses.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=31), nullable=False),
                    sa.Column('content', sa.String(length=2047), nullable=False),
                    sa.Column('sender', sa.String(length=4), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    conn = op.get_bind()
    conn.execute(
        sa.text("INSERT INTO roles (name) VALUES (:name)"),
        [{"name": "admin"}, {"name": "user"}]
    )

    now = datetime.now()
    conn.execute(
        sa.text("""
                INSERT INTO user_statuses (name, modified_date)
                VALUES (:name, :modified_date)
            """),
        [
            {"name": "active", "modified_date": now},
            {"name": "inactive", "modified_date": now}
        ]
    )

    conn.execute(
        sa.text("""
                    INSERT INTO chat_statuses (name, modified_date)
                    VALUES (:name, :modified_date)
                """),
        [
            {"name": "active", "modified_date": now},
            {"name": "inactive", "modified_date": now}
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats')
    op.drop_table('users')
    op.drop_table('user_statuses')
    op.drop_table('roles')
    op.drop_table('chat_statuses')
    # ### end Alembic commands ###
