"""limitation

Revision ID: 603cad2bc340
Revises: fc1c2663012b
Create Date: 2025-10-25 00:12:33.144243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603cad2bc340'
down_revision: Union[str, Sequence[str], None] = 'fc1c2663012b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_configuration', sa.Column('limit_interval_seconds', sa.Integer(), nullable=False))
    op.add_column('chatbot_configuration', sa.Column('limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_configuration', 'limit')
    op.drop_column('chatbot_configuration', 'limit_interval_seconds')
    # ### end Alembic commands ###
