"""configuration

Revision ID: 8b15c8007ad8
Revises: a8fb7c78065a
Create Date: 2025-09-11 15:43:35.258638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from weschatbot.models.user import Collection, CollectionStatus, ChatbotConfiguration # noqa

# revision identifiers, used by Alembic.
revision: str = '8b15c8007ad8'
down_revision: Union[str, Sequence[str], None] = 'a8fb7c78065a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_configuration',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('prompt', sa.Text(), nullable=True),
                    sa.Column('collection_id', sa.Integer(), nullable=True),
                    sa.Column('similar_threshold', sa.Float(), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    # add_chatbot_configuration()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_configuration')
    # ### end Alembic commands ###
