"""queries table

Revision ID: a1c7b6937506
Revises: fb0b0e814e1e
Create Date: 2025-10-07 22:19:00.191006

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1c7b6937506'
down_revision: Union[str, Sequence[str], None] = 'fb0b0e814e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('message_id', sa.Integer(), nullable=True),
                    sa.Column('document_id', sa.Integer(), nullable=False),
                    sa.Column('row_id', sa.BigInteger(), nullable=False),
                    sa.Column('document_text', sa.Text(), nullable=False),
                    sa.Column('cosine_score', sa.Float(), nullable=False),
                    sa.Column('rank', sa.Integer(), nullable=False),
                    sa.Column('collection_id', sa.Integer(), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
                    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
                    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    # ### end Alembic commands ###
