"""add converted path

Revision ID: a8fb7c78065a
Revises: 051438aeec89
Create Date: 2025-09-08 22:56:52.988015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fb7c78065a'
down_revision: Union[str, Sequence[str], None] = '051438aeec89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('converted_path', sa.String(length=2047), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'converted_path')
    # ### end Alembic commands ###
