"""bcrypt

Revision ID: b9617dd720c8
Revises: 603cad2bc340
Create Date: 2025-11-02 21:55:53.628655

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

from weschatbot.services.user_service import BcryptUserService
from weschatbot.utils.db import provide_session

# revision identifiers, used by Alembic.
revision: str = 'b9617dd720c8'
down_revision: Union[str, Sequence[str], None] = '603cad2bc340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@provide_session
def init_admin_user(session=None):
    user_service = BcryptUserService()
    user_service.create_user(user_name="bcrypt_admin", password="admin", role_name="admin", is_active=True)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
                    existing_type=mysql.VARCHAR(length=7),
                    nullable=True)
    # ### end Alembic commands ###

    init_admin_user()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
                    existing_type=mysql.VARCHAR(length=7),
                    nullable=False)
    # ### end Alembic commands ###
