"""update messages.content to text

Revision ID: d101dfb244f9
Revises: d3a110ffbaea
Create Date: 2025-08-11 11:12:03.796141

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd101dfb244f9'
down_revision: Union[str, Sequence[str], None] = 'd3a110ffbaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
                    existing_type=mysql.VARCHAR(length=2047),
                    type_=sa.Text(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
                    existing_type=sa.Text(),
                    type_=mysql.VARCHAR(length=2047),
                    existing_nullable=False)
    # ### end Alembic commands ###
