"""documents table

Revision ID: d3a110ffbaea
Revises: 51634997b174
Create Date: 2025-07-30 16:35:32.871410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd3a110ffbaea'
down_revision: Union[str, Sequence[str], None] = '51634997b174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('job_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=31), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('documents',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('path', sa.String(length=2047), nullable=False),
                    sa.Column('is_used', sa.Boolean(), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['status_id'], ['document_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('jobs',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=63), nullable=False),
                    sa.Column('class_name', sa.String(length=511), nullable=False),
                    sa.Column('params', sa.String(length=511), nullable=True),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['status_id'], ['job_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            INSERT INTO document_statuses(name) VALUES (:name)
            """
        ),
        [
            {"name": "new"},
            {"name": "in progress"},
            {"name": "done"},
            {"name": "failed"},
        ]
    )

    conn.execute(
        sa.text(
            """
            INSERT INTO job_statuses(name) VALUES (:name)
            """
        ), [
            {"name": "new"},
            {"name": "approved"},
            {"name": "scheduled"},
            {"name": "running"},
            {"name": "done"},
            {"name": "failed"},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('documents')
    op.drop_table('job_statuses')
    op.drop_table('document_statuses')
    # ### end Alembic commands ###
