"""add chatbot configuration

Revision ID: fb0b0e814e1e
Revises: 8b15c8007ad8
Create Date: 2025-09-23 23:19:53.401727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0b0e814e1e'
down_revision: Union[str, Sequence[str], None] = '8b15c8007ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_configuration', sa.Column('temperature', sa.Float(), nullable=False))
    op.add_column('chatbot_configuration', sa.Column('max_completion_tokens', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_configuration', 'max_completion_tokens')
    op.drop_column('chatbot_configuration', 'temperature')
    # ### end Alembic commands ###
