"""summary prompt

Revision ID: fc1c2663012b
Revises: a1c7b6937506
Create Date: 2025-10-22 21:54:43.680604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1c2663012b'
down_revision: Union[str, Sequence[str], None] = 'a1c7b6937506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_configuration', sa.Column('summary_prompt', sa.Text(), nullable=True))
    op.add_column('chatbot_configuration', sa.Column('analytic_topic_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_configuration', 'analytic_topic_prompt')
    op.drop_column('chatbot_configuration', 'summary_prompt')
    # ### end Alembic commands ###
